---
kind: ConfigMap
metadata:
  name: my-first-app-configmap
apiVersion: v1
data:
  index.html: |+
    <!DOCTYPE html>
    <html>
      <head>
        <title>My First App</title>
      </head>
        <body>
          <h1>My First App</h1>
        </body>
    </html>
  
  default.conf: |+
    server {
    listen       80;
    server_name  localhost;
      location / {
        root   /usr/share/nginx/html;
        index  index.html;
      }
      
      error_page 404 /index.html;
        location = /index.html {
          root /usr/share/nginx/html;
          internal;
       }
    }

